// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function Context():Promise<context.Context>;

export function RemoveMedia(arg1:string):Promise<void>;

export function RemoveSimilarImage(arg1:string):Promise<void>;
