// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';
import {handler} from '../models';

export function Context():Promise<context.Context>;

export function GetClassifyDir():Promise<string>;

export function GetShortcuts():Promise<Array<handler.ShortcutConfig>>;

export function GetUndoCount():Promise<number>;

export function MoveByShortcut(arg1:string,arg2:string):Promise<void>;

export function RemoveMedia(arg1:string):Promise<void>;

export function RemoveSimilarImage(arg1:string):Promise<void>;

export function SaveShortcuts(arg1:Array<handler.ShortcutConfig>):Promise<void>;

export function SelectShortcutTargetDir():Promise<string>;

export function SetClassifyDir(arg1:string):Promise<void>;

export function UndoMove():Promise<void>;
