// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Context() {
  return window['go']['app']['App']['Context']();
}

export function RemoveMedia(arg1) {
  return window['go']['app']['App']['RemoveMedia'](arg1);
}

export function RemoveSimilarImage(arg1) {
  return window['go']['app']['App']['RemoveSimilarImage'](arg1);
}
